apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec: 
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: contents-vol
      readOnly: true
  
  - name: cloner
    # 事前に`docker build --tag contents-cloner:0.1 .`実行
    # minikubeの場合WSL2のローカルのdockerイメージ使えないのでminikubeのdockerに切り替える必要ある
    image: contents-cloner:0.1 
    env:
    - name: CONTENTS_SOURCE_URL
      value: "https://github.com/takara9/web-contents"
    volumeMounts:
    - mountPath: /data
      name: contents-vol

  volumes:
  - name: contents-vol
    emptyDir: {}